# Generated by Django 3.2.7 on 2021-10-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('edad', models.IntegerField(default=0)),
                ('fotografia', models.ImageField(upload_to='usuarios')),
                ('contrasena', models.CharField(max_length=100)),
                ('intentos', models.IntegerField(default=0)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('direccion_ip', models.CharField(max_length=15)),
                ('slug', models.SlugField(editable=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
