# Generated by Django 3.2.7 on 2021-11-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('fotografia', models.ImageField(upload_to='auth')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=0),
        ),
    ]
