# Generated by Django 3.2.7 on 2021-11-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_carrito_detallefactura_factura_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
